package:
  name: bm3d
  version: 0.1.0

source:
  git_url: https://github.com/gfacciol/bm3d
  git_tag: master
  patches:
    - 0001-Link-fftw-statically.patch
    - 0002-Install-binary-and-library.patch
    - 0003-Fix-shared-library-sources.patch
    - 0004-Link-fftwf-with-Bsymbolic.patch

build:
  number: 6
  ignore_run_exports:
    - fftw

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - fftw
    - libpng
    - libtiff
    - jpeg
  run:
    - libpng
    - libtiff
    - jpeg


about:
  home: https://github.com/gfacciol/bm3d
  license: GPLv3
  summary: 'bm3d'
